name: CI/CD for Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    environment: Main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetches code from GitHub

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          TAG=$(date +%Y%m%d%H%M%S)  # Generate a timestamp-based tag
          echo "Building Docker image with tag: $TAG"
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/restaurant-web:$TAG -t ${{ secrets.DOCKER_USERNAME }}/restaurant-web:latest .

          # Verify the built images
          docker images | grep ${{ secrets.DOCKER_USERNAME }}/restaurant-web

          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-web:$TAG
